[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/=node_modules/@spherex-xyz/openzeppelin-solidity/",
    "@ensdomains/=node_modules/@ensdomains/",
    "@spherex-xyz/=node_modules/@spherex-xyz/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
